apiVersion: v1
kind: Pod
spec:
  containers:
    - image: "jenkinsciinfra/builder:2.2.35"
      imagePullPolicy: "IfNotPresent"
      name: "jnlp"
      resources:
        limits:
          memory: "768Mi"
          cpu: "1"
        requests:
          memory: "768Mi"
          cpu: "1"
      securityContext:
        privileged: false
