apiVersion: v1
kind: Pod
spec:
  containers:
    - image: "jenkinsciinfra/builder:2.1.0"
      imagePullPolicy: "IfNotPresent"
      name: "jnlp"
      resources:
        limits:
          memory: "256Mi"
          cpu: "1"
        requests:
          memory: "256Mi"
          cpu: "1"
      securityContext:
        privileged: false
